name: lint workflow files

on:
  workflow_call:
    inputs:
      runner:
        type: string
        default: ubuntu-latest

permissions: {}

jobs:
  actionlint:
    name: actionlint
    runs-on: ${{ inputs.runner }}
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
          sparse-checkout: |
            .github/workflows
            .github/actions
          sparse-checkout-cone-mode: false
      - shell: bash
        run: |
          set -euo pipefail
          cat > "${RUNNER_TEMP}/aqua.yaml" <<'EOF'
          checksum:
            enabled: true
          registries:
            - type: standard
              ref: v4.529.1 # renovate: depName=aquaproj/aqua-registry
          packages:
            - name: rhysd/actionlint@v1.7.12
          EOF
          echo "AQUA_GLOBAL_CONFIG=${RUNNER_TEMP}/aqua.yaml" >> "${GITHUB_ENV}"
      - uses: aquaproj/aqua-installer@a78671ff723534c879a9c8aa62c99a3a05dddb49 # v4.0.5
        with:
          aqua_version: v2.60.1
      - shell: bash
        run: |
          set -euo pipefail
          actionlint -color

  ghalint:
    name: ghalint
    runs-on: ${{ inputs.runner }}
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
          sparse-checkout: |
            .github/workflows
            .github/actions
          sparse-checkout-cone-mode: false
      - shell: bash
        run: |
          set -euo pipefail
          cat > "${RUNNER_TEMP}/aqua.yaml" <<'EOF'
          checksum:
            enabled: true
          registries:
            - type: standard
              ref: v4.529.1 # renovate: depName=aquaproj/aqua-registry
          packages:
            - name: suzuki-shunsuke/ghalint@v1.5.6
          EOF
          echo "AQUA_GLOBAL_CONFIG=${RUNNER_TEMP}/aqua.yaml" >> "${GITHUB_ENV}"
      - uses: aquaproj/aqua-installer@a78671ff723534c879a9c8aa62c99a3a05dddb49 # v4.0.5
        with:
          aqua_version: v2.60.1
      - shell: bash
        run: |
          set -euo pipefail
          ghalint run

  zizmor:
    name: zizmor
    runs-on: ${{ inputs.runner }}
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
          sparse-checkout: |
            .github/workflows
            .github/actions
          sparse-checkout-cone-mode: false
      - uses: zizmorcore/zizmor-action@192e21d79ab29983730a13d1382995c2307fbcaa # v0.5.7
        with:
          # Set to true if GitHub Advanced Security is available
          advanced-security: false

  ghasec:
    name: ghasec
    runs-on: ${{ inputs.runner }}
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
          sparse-checkout: |
            .github/workflows
            .github/actions
          sparse-checkout-cone-mode: false
      - uses: koki-develop/ghasec-action@2810775d2a300cb3fd9583c36c05b5ee3310c5b8 # v1.1.1
